### ISSUE TITLE
Wording of Connector Status

### ISSUE THREAD

**Issue by tmberthold** [sovity/authority-portal#270]
# Enhancement

## Description
```
The status of connectors are inconsistently named.
- A green status is named "ONLINE" or "RUNNING". Please use "ONLINE" for both.
```

![image](https://github.com/user-attachments/assets/b5747ee1-4e21-4602-94a9-673a1c76e455)

![image](https://github.com/user-attachments/assets/45372afd-34e7-487f-880b-2000ae1627ba)

Also was mentioned:
`- A red status is named "DEAD" or "OFFLINE". Please use "OFFLINE" for both.`
but this could have been (partially) addressed already: https://github.com/sovity/authority-portal/issues/184

## Stakeholders

MDS

## Solution Proposal and Work Breakdown

```[tasklist]
- [ ] Fix the GitHub Projects Labels, Sprint and other Metadata
- [ ] Refine a Solution Proposal / Work Breakdown
```

**Comment by kamilczaja** [comment]
Statuses for CaaS connectors requested via the Portal are more detailed because we get a detailed status report from the CaaS Management Portal.

Other connectors have only limited status reporting (Online/Offline) because the status is determined via the catalog crawler.

I guess we can map the CaaS status names to more consistent ones
