### ISSUE TITLE
MDS Logo

### ISSUE THREAD

**Issue by jridderbusch** [sovity/authority-portal#57]
### Description - What happened? *

The MDS Logo in the upper right corner is not compliant with the cooperate design of the MDS.

Please use the logo that is in the styleguide. Since we might get a Logo that also displays the words "MDS Portal" it would be good, if the image could easily be changed. Feel free to get back to me, if this is unclear.

**Additional**
In the initial bug report I only pointed out the logo that is used on the menu bar. The same is true for the logo in the registration process. Please stick to the styleguide wherever you're embedding the MDS Logo.

### Expected Behavior *

/

### Observed Behavior *

/

### Screenshots

<img width="298" alt="MDS_Logo" src="https://github.com/sovity/authority-portal/assets/36418748/272b9791-82c4-4afe-bd72-6ac498bb89af">

**Comment by kamilczaja** [comment]
I feel like we're missing some context here

**Comment by illfixit** [comment]
@jkbquabeck should we ping Vanessa?

**Comment by jkbquabeck** [comment]
That looks like the upper left corner to me

**Comment by jkbquabeck** [comment]
![image](https://github.com/sovity/authority-portal/assets/139474964/fb7e249e-36cc-4dbe-8ac5-9cdd8c687d07)
@drmVR are you referring to this logo and "Data Space" in one row?

**Comment by drmVR** [comment]
Sorry for the confusion: I ment the logo in the upper **left** corner - my mistake.
The Logo Jakob shared is correct as "Data Space" is in one row. We have to stick to the styleguide with this.
I'd like to add that the logo in the registration process is also not compliant with the cooperate design. Please also use one of the logos of the styleguide for this.

**Comment by illfixit** [comment]
@drmVR hi! do you mean this logo in the registration process (below)? And I suppose we don't have logo for MDS Portal? so we're using the icon and the text in default font (Arial and we can easily make Data Space to appear always on one line). Would it be okay?

![Image](https://github.com/sovity/authority-portal/assets/66363651/60629849-f41c-4f0e-8acd-a70b47221011)

**Comment by drmVR** [comment]
Yes, this is the logo I refered to in my last comment. Unfortunately we do not have a specific logo for the MDS Portal which is why we have to go with the usual MDS logo.
From what you have written, I assume that you are currently embedding the logo as a separate picture and added the wording "Mobility Data Space" separatly. I would prefer it if you could use the icon (logo + text) from the styleguide as there are rules for e.g. the space around the logo and how exactly logo and wording should be placed. There is also a black and white version of the logo which would fit the style of the registration pages. 
You should have received the styleguide, but let me now if you want me to share it again. I don't want to put public on github but I can send it to you via mail.
